name: Create Pipeline

on:
  push:
    branches: main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - run: echo "run new ci"
=======
      - run: echo "run new ci 2"
>>>>>>> dev
